### ISSUE TITLE
Asset size

### ISSUE THREAD

**Issue by Zen0x7** [sauromates/vue-gravatar#7]
I'm using vite and when i implement this package, it use almost 481,7kb of space of the bundle.

# With

![image](https://github.com/user-attachments/assets/4bc12680-ad01-4625-b8b2-6b09dc091f7a)

# Without

![image](https://github.com/user-attachments/assets/aced29da-3a25-4cec-ba76-c8a214e9b4bf)

Isn't a huge problem but this issue is a concern. To be honest, it seems linked to buffer library which provides web browser compatibility but with a huge cost.

Anyways, thanks for your library.

**Comment by sauromates** [comment]
Thanks for reaching out! 

I totally see how this can be a concern. The package size is indeed too large due to polyfills used for hashing. 

I'll look into it as soon as I can.

**Comment by sauromates** [comment]
@Zen0x7 just pushed a new version of the package, please see if it resolves the bundle size issue for you.

**Comment by Zen0x7** [comment]
@sauromates now appears the following: 

![image](https://github.com/user-attachments/assets/80b7b1b2-314d-410a-8baf-22f819fd93d7)

**Comment by Zen0x7** [comment]
The previous can be fixed by adding `js-sha256` to my project but sounds weird. 

![image](https://github.com/user-attachments/assets/f14de41e-d995-44da-a0aa-5770932e3396)

At the end of the day, it solves the problem.

So your package now is a dependency of [this project](https://github.com/Zen0x7/ServiceBench).

**Comment by sauromates** [comment]
Hm. Sorry to hear about the error, I'll try to investigate. The `js-sha256` is externalized already and shouldn't trigger this error, Yarn should have loaded it as a peer dependency. Thanks for providing a project link, I'll try to reproduce. 

Anyways, I'm glad to hear that you have managed to integrate the library into your project. I will keep the issue open until I'm certain about the cause of this issue.

**Comment by sauromates** [comment]
@Zen0x7 I've deployed the project you provided locally but couldn't get the error you've provided. Can you please provide some steps to reproduce it? 

Using my own email instead of yours in the seeder gives me this without errors (on fresh install):

![image](https://github.com/user-attachments/assets/e4bee913-54d5-4d0a-b201-c8c812b0c624).

**Comment by Zen0x7** [comment]
@sauromates just remove `js-sha256` as a dependency and try to build again.

**Comment by sauromates** [comment]
@Zen0x7 I believe I've managed to resolve the issue. 

Somehow Yarn doesn't install peer dependencies automatically like NPM does. I've moved `js-sha256` to direct dependencies and tested on your project - looks like everything working as it should be now.

![image](https://github.com/user-attachments/assets/8778465c-f853-457d-9951-8e0e270320f6)


Please do try the latest release. Feel free to close the issue if everything is fine.

**Comment by Zen0x7** [comment]
@sauromates Yeah, seems like all is fine right now. 

Thanks a lot. This is one good package. I'll use a couple of times in twice projects.
